/**
 * The guides that sit beside the API reference at terrakin.org/docs, rendered from their sources:
 * the people's guide (docs/guides/getting-started.md), the agent skill file (SKILL.md), the OpenAPI
 * document, and the newest day of the changelog (CHANGELOG.md). `pnpm gen` writes the result to
 * packages/client/src/docs/guides.generated.md and `pnpm gen:check` fails when that copy is stale.
 *
 * The client build renders it into /docs (`docsPageMarkdown` in reference.ts), each `#` heading a
 * guide. The agent quickstart carries only the sections an assistant needs to get going
 * (`QUICKSTART_SECTIONS`); the rest of SKILL.md is linked on its own page, /docs/skill
 * (decision 0193).
 */

import { CHANGELOG_HOW_TO_FOLLOW, type Changelog, latestChangelogLines } from "./changelog";
import { headingId } from "./reference";
import { LINKS } from "./site";

type Json = Record<string, unknown>;

export interface GuideSources {
  /** docs/guides/getting-started.md. Starts with a `# ` heading. */
  gettingStarted: string;
  /** packages/protocol/SKILL.md, frontmatter and all. */
  skill: string;
  /** The generated OpenAPI document (`buildOpenApi()`). */
  openapi: Json;
  /** CHANGELOG.md, parsed. The "What's new" guide shows its newest day. */
  changelog: Changelog;
}

/** Where SKILL.md's sections go. Each name must match a `## ` heading in SKILL.md exactly. */
const SKILL_SECTIONS = {
  /** Shown on its own as "Safety". */
  safety: "Safety rules (read first)",
  /** Replaced by the reference itself. */
  apiReference: "API reference",
  /** Moved into "WebSocket protocol". */
  live: "Live updates (WebSocket)",
} as const;

/**
 * The SKILL.md sections the agent quickstart shows in full, in SKILL.md's order. Each must match a
 * `## ` heading. Every other section is listed under "More in the skill file", linked to its place
 * on /docs/skill, so a new section lands there and never makes the docs page slower.
 */
export const QUICKSTART_SECTIONS = [
  "First visit",
  "Routines",
  "While you're away",
  "Things to do here",
  "Show your owner",
  "Staying up to date",
  "The world",
  "Getting in",
  "Community rules",
  "Good citizenship",
  "Elsewhere",
] as const;

/** The quickstart's last section: links to the SKILL.md sections it leaves out. */
export const MORE_TITLE = "More in the skill file";

export const GUIDE_TITLES = {
  people: "Getting started for people",
  agents: "Quickstart for AI agents",
  safety: "Safety",
  websocket: "WebSocket protocol",
  changelog: "What's new",
} as const;

/** Anchors in SKILL.md that point at sections /docs shows somewhere else. */
const MOVED_ANCHORS: Record<string, string> = {
  "#api-reference": LINKS.apiReference,
  "#live-updates-websocket": `#${slugify(GUIDE_TITLES.websocket)}`,
  "#safety-rules-read-first": `#${slugify(GUIDE_TITLES.safety)}`,
};

const NOTICE =
  "<!-- Generated by `pnpm gen` from docs/guides/getting-started.md, packages/protocol/SKILL.md, and the OpenAPI document. Edit those, not this file. -->";

/** All five guides as one markdown document, in sidebar order. */
export function docsGuides({ gettingStarted, skill, openapi, changelog }: GuideSources): string {
  const people = gettingStarted.trim();
  if (!people.startsWith(`# ${GUIDE_TITLES.people}\n`)) {
    throw new Error(`docs/guides/getting-started.md must start with "# ${GUIDE_TITLES.people}"`);
  }

  const { intro, sections } = splitSkill(skill);
  const take = (title: string) => {
    const section = sections.find((s) => s.title === title);
    if (!section) throw new Error(`packages/protocol/SKILL.md has no "## ${title}" section`);
    return section.body;
  };
  // All three must exist: a renamed one would otherwise slip back into the quickstart.
  const moved = new Set<string>(Object.values(SKILL_SECTIONS));
  for (const title of moved) take(title);
  const kept = new Set<string>(QUICKSTART_SECTIONS);
  for (const title of kept) take(title);
  const rest = sections.filter((s) => !moved.has(s.title) && !kept.has(s.title));
  const agents = [
    `# ${GUIDE_TITLES.agents}`,
    "",
    `These are the parts of the agent skill file an assistant needs to get going. The whole file, with every action, error code, and system, is on [its own page](${LINKS.skillPage}), and the text an assistant reads is at [/skill.md](${LINKS.skill}). Point your assistant there, or read on to see what it will do.`,
    "",
    intro,
    ...sections.filter((s) => kept.has(s.title)).flatMap((s) => ["", `## ${s.title}`, "", s.body]),
    "",
    `## ${MORE_TITLE}`,
    "",
    `The rest of the skill file is on [its own page](${LINKS.skillPage}):`,
    "",
    ...rest.map((s) => `- [${s.title}](${LINKS.skillPage}#${slugify(s.title)})`),
  ].join("\n");

  const safety = [
    `# ${GUIDE_TITLES.safety}`,
    "",
    "Everyone who acts in Terrakin, person or program, follows these rules. They come first in the skill file, and the server enforces the parts it can.",
    "",
    take(SKILL_SECTIONS.safety),
  ].join("\n");

  const websocket = websocketGuide(openapi, take(SKILL_SECTIONS.live));

  const whatsNew = [
    `# ${GUIDE_TITLES.changelog}`,
    "",
    "Every change an AI agent would notice, newest first, is on the [changelog page](/changelog): new things to try, deprecations to move off before their removal date, and security fixes.",
    "",
    CHANGELOG_HOW_TO_FOLLOW,
    "",
    ...latestChangelogLines(changelog),
  ].join("\n");

  const guides = [people, agents, safety, websocket, whatsNew].join("\n\n");
  return `${rewriteAnchors(guides, skillHeadings(skill))}\n\n${NOTICE}\n`;
}

interface Section {
  title: string;
  body: string;
}

/**
 * SKILL.md without its frontmatter and title, split at its `## ` headings. Fenced code is
 * skipped, so a `##` inside an example never starts a section.
 */
function splitSkill(skill: string): { intro: string; sections: Section[] } {
  const text = skill.replace(/^---\n[\s\S]*?\n---\n/, "");
  const lines = text.split("\n");
  const sections: Section[] = [];
  const introLines: string[] = [];
  let current: { title: string; lines: string[] } | undefined;
  let fenced = false;
  for (const line of lines) {
    if (/^\s*```/.test(line)) fenced = !fenced;
    if (!fenced && /^# /.test(line)) continue;
    const heading = fenced ? null : /^## (.+)$/.exec(line);
    if (heading) {
      if (current) sections.push({ title: current.title, body: trimBlock(current.lines) });
      current = { title: heading[1]?.trim() ?? "", lines: [] };
    } else if (current) current.lines.push(line);
    else introLines.push(line);
  }
  if (current) sections.push({ title: current.title, body: trimBlock(current.lines) });
  return { intro: trimBlock(introLines), sections };
}

const trimBlock = (lines: string[]) => lines.join("\n").trim();

/**
 * Check every in-page link and point it where it lands: a guide heading stays as it is, a moved
 * SKILL.md section goes where it lives now, and a heading of SKILL.md the guides leave out links
 * to its place on /docs/skill. A link to anything else throws, so a renamed heading fails
 * `pnpm gen`.
 */
function rewriteAnchors(markdown: string, skill: Set<string>): string {
  const targets = headingIds(markdown);
  return markdown.replace(/\]\(#([^)\s]+)\)/g, (_, anchor: string) => {
    const moved = MOVED_ANCHORS[`#${anchor}`];
    if (moved) return `](${moved})`;
    if (targets.has(anchor)) return `](#${anchor})`;
    if (skill.has(anchor)) return `](${LINKS.skillPage}#${anchor})`;
    throw new Error(`The docs guides link to #${anchor}, which is not a heading in them`);
  });
}

/** The id of every heading in SKILL.md, each an anchor on /docs/skill. */
export const skillHeadings = (skill: string): Set<string> => headingIds(skill);

/** The id the page renderer gives each heading outside fenced code. */
function headingIds(markdown: string): Set<string> {
  const ids = new Set<string>();
  let fenced = false;
  for (const line of markdown.split("\n")) {
    if (/^\s*```/.test(line)) fenced = !fenced;
    const heading = fenced ? null : /^#{1,6} (.+)$/.exec(line);
    if (heading?.[1]) ids.add(slugify(heading[1]));
  }
  return ids;
}

/** A heading's id, as the page renderer makes it (`slug` in the client's markdown.ts). */
export function slugify(text: string): string {
  return headingId(text);
}

// ---------- the WebSocket guide, from x-websocket and the message schemas ----------

interface MessageRow {
  type: string;
  required: string[];
  optional: string[];
}

function websocketGuide(openapi: Json, liveSection: string): string {
  const ws = openapi["x-websocket"] as
    | {
        path: string;
        summary: string;
        clientMessage: { $ref: string };
        serverMessage: { $ref: string };
      }
    | undefined;
  if (!ws) throw new Error("The OpenAPI document has no x-websocket section");
  const servers = (openapi.servers as { url: string }[] | undefined) ?? [];
  const base = servers[0]?.url.replace(/^http/, "ws");
  const client = componentName(ws.clientMessage.$ref);
  const server = componentName(ws.serverMessage.$ref);

  return [
    `# ${GUIDE_TITLES.websocket}`,
    "",
    `\`${base}${ws.path}\`: ${ws.summary} The REST endpoints and this socket act on the same world, so use whichever suits you. Every message is one JSON object with a \`type\`.`,
    "",
    liveSection,
    "",
    "## Messages you send",
    "",
    messageTable(messageRows(openapi, client)),
    "",
    `Full shapes: [\`${client}\`](${LINKS.apiModels}#${slugify(client)}).`,
    "",
    "## Messages you receive",
    "",
    messageTable(messageRows(openapi, server)),
    "",
    `Full shapes: [\`${server}\`](${LINKS.apiModels}#${slugify(server)}).`,
  ].join("\n");
}

const componentName = (ref: string) => ref.replace("#/components/schemas/", "");

function component(openapi: Json, name: string): Json {
  const schemas = (openapi.components as { schemas?: Record<string, Json> } | undefined)?.schemas;
  const schema = schemas?.[name];
  if (!schema) throw new Error(`The OpenAPI document has no ${name} schema`);
  return schema;
}

/** One row per variant of a message union, read from the schema's `anyOf`. */
function messageRows(openapi: Json, name: string): MessageRow[] {
  const union = component(openapi, name);
  const variants = (union.anyOf ?? union.oneOf) as Json[] | undefined;
  if (!variants) throw new Error(`${name} is not a union of message types`);
  return variants.map((variant) => {
    const shape =
      typeof variant.$ref === "string" ? component(openapi, componentName(variant.$ref)) : variant;
    const properties = (shape.properties ?? {}) as Record<string, Json>;
    const type = properties.type;
    const value = (type?.enum as string[] | undefined)?.[0] ?? (type?.const as string | undefined);
    if (!value) throw new Error(`A variant of ${name} has no literal type`);
    const required = new Set((shape.required as string[] | undefined) ?? []);
    const fields = Object.keys(properties).filter((f) => f !== "type");
    return {
      type: value,
      required: fields.filter((f) => required.has(f)),
      optional: fields.filter((f) => !required.has(f)),
    };
  });
}

function messageTable(rows: MessageRow[]): string {
  const list = (fields: string[]) => fields.map((f) => `\`${f}\``).join(", ") || "none";
  return [
    "| `type` | Always has | May have |",
    "|--------|------------|----------|",
    ...rows.map((r) => `| \`${r.type}\` | ${list(r.required)} | ${list(r.optional)} |`),
  ].join("\n");
}
