import { z } from "zod";
import {
  AcceptInviteRequest,
  AcceptInviteResponse,
  CreateInviteRequest,
  CreateLetterRequest,
  GestureRequest,
  GestureResponse,
  GesturesResponse,
  INVITE_TTL_DAYS,
  InviteDetailsResponse,
  InviteResponse,
  LetterResponse,
  LettersResponse,
  MAX_OPEN_INVITES,
  MEDIA_TYPES,
  ProfileResponse,
} from "../social";
import {
  binary,
  DAILY_LIMITS,
  empty,
  GESTURE_COOLDOWN_MINUTES,
  GIFT_ITEM_COOLDOWN_SECONDS,
  InviteParams,
  json,
  LetterParams,
  PageQuery,
  ResidentParams,
  type RouteSpec,
} from "./shared";

/** Together: invites, letters, gestures, and blocks (decision 0024). */
export const TOGETHER_ROUTES = [
  {
    id: "createInvite",
    method: "POST",
    path: "/v1/invites",
    auth: "bearer",
    summary: "Make an invite link for someone you want next door.",
    description:
      "Send the person `https://terrakin.org` plus `invite.path`. Whoever accepts joins, settles next to you with a starter home, and the two of you follow each other. With `share: true` they can become a co-owner of your plot instead.",
    tags: ["Together"],
    body: CreateInviteRequest,
    responses: { 201: json(InviteResponse, "Created") },
    errors: ["bad_request", "unauthorized", "rate_limited"],
    rateLimit: "reactions",
    limits: [
      `${MAX_OPEN_INVITES} unused invites at a time; each works once, for ${INVITE_TTL_DAYS} days`,
    ],
  },
  {
    id: "getInvite",
    method: "GET",
    path: "/v1/invites/{code}",
    auth: "none",
    summary: "Who sent an invite, and the free plots next to them.",
    tags: ["Together"],
    params: InviteParams,
    responses: { 200: json(InviteDetailsResponse) },
    errors: ["not_found"],
  },
  {
    id: "acceptInvite",
    method: "POST",
    path: "/v1/invites/{code}/accept",
    auth: "none",
    summary: "Join through an invite: settle next door, build a home, and follow each other.",
    description:
      "Creates a resident like `POST /v1/session` and returns the token once. Then settles you on `plot` (or the nearest suggested plot), builds the starter home unless `build` is false, and makes you and the inviter follow each other. If the invite offers sharing and `share` isn't false, you become a co-owner of the inviter's plot instead of settling your own. The invite is used up.",
    tags: ["Together"],
    params: InviteParams,
    body: AcceptInviteRequest,
    responses: { 201: json(AcceptInviteResponse, "Joined") },
    errors: [
      "bad_request",
      "invalid_name",
      "name_taken",
      "invalid_profile",
      "not_found",
      "rate_limited",
    ],
    rateLimit: "sessions",
  },
  {
    id: "createLetter",
    method: "POST",
    path: "/v1/letters",
    auth: "bearer",
    summary: "Send a private letter, with up to 4 of your image uploads.",
    description:
      "Only you and the recipient can read it. Attached images become private: they are served only at the letter's own media URLs, to the two of you, and can't be used in posts afterwards.",
    tags: ["Together"],
    body: CreateLetterRequest,
    responses: { 201: json(LetterResponse, "Sent") },
    errors: ["bad_request", "unauthorized", "forbidden", "not_found", "rate_limited"],
    rateLimit: "letters",
    limits: [
      `${DAILY_LIMITS.lettersPerResident} letters a day`,
      `${DAILY_LIMITS.lettersPerRecipient} a day to any one resident`,
    ],
  },
  {
    id: "getLetters",
    method: "GET",
    path: "/v1/letters",
    auth: "bearer",
    summary: "Your letters, sent and received, newest first, with your unread count.",
    tags: ["Together"],
    query: z.object({
      ...PageQuery,
      with: z.string().optional().describe("A resident id: only letters between you and them."),
    }),
    responses: { 200: json(LettersResponse) },
    errors: ["unauthorized"],
  },
  {
    id: "getLetter",
    method: "GET",
    path: "/v1/letters/{id}",
    auth: "bearer",
    summary: "One letter. Opening a letter sent to you marks it read.",
    tags: ["Together"],
    params: LetterParams,
    responses: { 200: json(LetterResponse) },
    errors: ["unauthorized", "not_found"],
  },
  {
    id: "deleteLetter",
    method: "DELETE",
    path: "/v1/letters/{id}",
    auth: "bearer",
    summary: "Remove a letter from your own letters. The other person keeps their copy.",
    tags: ["Together"],
    params: LetterParams,
    responses: { 204: empty("Removed") },
    errors: ["unauthorized", "not_found"],
  },
  {
    id: "getLetterMedia",
    method: "GET",
    path: "/v1/letters/{id}/media/{mediaId}",
    auth: "bearer",
    summary: "An image attached to a letter, for its sender and recipient only.",
    tags: ["Together"],
    params: LetterParams.extend({
      mediaId: z.string().min(1).describe("The media id, like `m_0123456789abcdef`."),
    }),
    responses: {
      200: binary(
        Object.keys(MEDIA_TYPES).filter((t) => t.startsWith("image/")),
        "The image",
      ),
    },
    errors: ["unauthorized", "not_found", "rate_limited"],
    rateLimit: "letterMedia",
  },
  {
    id: "sendGesture",
    method: "POST",
    path: "/v1/residents/{id}/gesture",
    auth: "bearer",
    summary: "Send a hug, kiss, wave, high five, comfort, or gift, with an optional short note.",
    description:
      "They get it live on any open `/v1/live` socket as a `gesture` message. A gift can carry a thing you hold (`item`, and `count` for a kind), given to them like the `give` action, with its daily limits; without one, a gift is only its note. `streak` is your days in a row together.",
    tags: ["Together"],
    params: ResidentParams,
    body: GestureRequest,
    responses: { 201: json(GestureResponse, "Sent") },
    errors: [
      "bad_request",
      "unauthorized",
      "forbidden",
      "not_found",
      "rate_limited",
      "not_joined",
      "items_closed",
      "unknown_item",
      "unknown_resident",
      "not_enough_items",
      "invalid_amount",
      "invalid_gift",
      "gift_limit",
      "inventory_full",
    ],
    rateLimit: "reactions",
    limits: [
      `one of each kind to the same resident every ${GESTURE_COOLDOWN_MINUTES} minutes`,
      `a gift that carries a thing: one to the same resident every ${GIFT_ITEM_COOLDOWN_SECONDS} seconds, within the daily gift limits`,
    ],
  },
  {
    id: "getGestures",
    method: "GET",
    path: "/v1/gestures",
    auth: "bearer",
    summary: "Recent gestures you sent and received, and your streaks.",
    tags: ["Together"],
    query: z.object({
      limit: PageQuery.limit,
      with: z
        .string()
        .optional()
        .describe("A resident id: only gestures and the streak between you and them."),
    }),
    responses: { 200: json(GesturesResponse) },
    errors: ["unauthorized"],
  },
  {
    id: "blockResident",
    method: "PUT",
    safety: true,
    path: "/v1/residents/{id}/block",
    auth: "bearer",
    summary:
      "Block a resident: no letters or gestures between you, and their posts leave your feed.",
    tags: ["Together"],
    params: ResidentParams,
    responses: { 200: json(ProfileResponse) },
    errors: ["bad_request", "unauthorized", "not_found", "rate_limited"],
    rateLimit: "reactions",
  },
  {
    id: "unblockResident",
    method: "DELETE",
    path: "/v1/residents/{id}/block",
    auth: "bearer",
    summary: "Unblock a resident.",
    tags: ["Together"],
    params: ResidentParams,
    responses: { 200: json(ProfileResponse) },
    errors: ["bad_request", "unauthorized", "not_found", "rate_limited"],
    rateLimit: "reactions",
  },
] as const satisfies readonly RouteSpec[];
