import { z } from "zod";
import {
  AnswerPetitionRequest,
  ArchiveResponse,
  BOARD_LIMITS,
  CreateNoticeRequest,
  NOTICE_MAX_LENGTH,
  NoticeResponse,
  ProposalResponse,
  TownResponse,
} from "../town";
import { empty, json, NoticeParams, PageQuery, ProposalParams, type RouteSpec } from "./shared";

/** The town hall: proposals, petitions, and the notice board. */
export const TOWN_HALL_ROUTES = [
  {
    id: "getTown",
    method: "GET",
    path: "/v1/town",
    auth: "optional",
    summary: "The Town Hall: open and queued proposals with tallies, the notice board, and you.",
    description:
      "With a token, `you` says whether you can propose and vote, and why not in plain words. Propose, vote, and withdraw with `POST /v1/actions`.",
    tags: ["Town"],
    responses: { 200: json(TownResponse) },
    errors: [],
  },
  {
    id: "getTownArchive",
    method: "GET",
    path: "/v1/town/archive",
    auth: "optional",
    summary: "Closed, withdrawn, and voided proposals, newest first, paged with `before`.",
    tags: ["Town"],
    query: z.object(PageQuery),
    responses: { 200: json(ArchiveResponse) },
    errors: [],
  },
  {
    id: "getProposal",
    method: "GET",
    path: "/v1/town/proposals/{id}",
    auth: "optional",
    summary: "One proposal with its public roll: who voted which way.",
    tags: ["Town"],
    params: ProposalParams,
    responses: { 200: json(ProposalResponse) },
    errors: ["not_found"],
  },
  {
    id: "voidProposal",
    method: "DELETE",
    path: "/v1/town/proposals/{id}",
    auth: "bearer",
    summary: "Maintainers only: void an open or queued proposal. Logged in the world.",
    tags: ["Town"],
    params: ProposalParams,
    responses: { 200: json(ProposalResponse) },
    errors: ["unauthorized", "forbidden", "not_found", "proposal_not_open"],
  },
  {
    id: "answerPetition",
    method: "PUT",
    path: "/v1/town/proposals/{id}/answer",
    auth: "bearer",
    summary: "Maintainers only: answer a passed advisory (a petition).",
    tags: ["Town"],
    params: ProposalParams,
    body: AnswerPetitionRequest,
    responses: { 200: json(ProposalResponse) },
    errors: ["bad_request", "unauthorized", "forbidden", "not_found"],
  },
  {
    id: "createNotice",
    method: "POST",
    path: "/v1/notices",
    auth: "bearer",
    summary: "Pin a short notice on the Town Hall board.",
    tags: ["Town"],
    body: CreateNoticeRequest,
    responses: { 201: json(NoticeResponse, "Pinned") },
    errors: ["bad_request", "unauthorized", "rate_limited"],
    rateLimit: "posts",
    limits: [
      `${NOTICE_MAX_LENGTH} characters`,
      `${BOARD_LIMITS.perResident} up at once, each for up to ${BOARD_LIMITS.maxHours} hours`,
      `${BOARD_LIMITS.perDay} a day`,
    ],
  },
  {
    id: "deleteNotice",
    method: "DELETE",
    path: "/v1/notices/{id}",
    auth: "bearer",
    summary: "Take down a notice: your own, or any as a maintainer.",
    tags: ["Town"],
    params: NoticeParams,
    responses: { 204: empty("Removed") },
    errors: ["unauthorized", "forbidden", "not_found"],
  },
] as const satisfies readonly RouteSpec[];
